@extends('layouts.portal')

@section('title', 'Finance')

@section('content')
    <header class="page-heading page-heading-actions">
        <div>
            <p class="eyebrow">Finance office</p>
            <h1>Fees and Payments</h1>
            <p>Create fee items, generate invoices, record verified office payments, review balances and reconcile collections.</p>
        </div>
        @if (auth()->user()->hasPermission('finance.configure_gateways'))
            <a class="secondary-link" href="{{ route('web.admin.finance.gateways.index') }}">Gateway settings</a>
        @endif
    </header>

    <section class="metric-row metric-row-5" aria-label="Finance summary">
        <article class="metric-item"><span>Total billed</span><strong>₦{{ number_format($overview['total_billed'], 2) }}</strong></article>
        <article class="metric-item"><span>Collected</span><strong>₦{{ number_format($overview['total_collected'], 2) }}</strong></article>
        <article class="metric-item"><span>Outstanding</span><strong>₦{{ number_format($overview['outstanding_total'], 2) }}</strong></article>
        <article class="metric-item"><span>Student debtors</span><strong>{{ number_format($overview['student_debtor_count']) }}</strong></article>
        <article class="metric-item"><span>Collection rate</span><strong>{{ number_format($overview['collection_rate'], 1) }}%</strong></article>
    </section>

    <nav class="workspace-tabs" aria-label="Finance sections">
        @foreach ([
            'overview' => 'Overview',
            'fee-items' => 'Fee Catalogue',
            'invoices' => 'Generate Invoices',
            'manual-payment' => 'Record Payment',
            'student-balances' => 'Student Balances',
            'class-bills' => 'Class Bills',
            'payment-summary' => 'Payment Summary',
            'recent-payments' => 'Recent Payments',
            'overpayments' => 'Overpayments',
            'payment-progression' => 'Progression',
        ] as $key => $label)
            <a href="{{ route('web.admin.finance.index', ['section' => $key]) }}" @class(['is-active' => $activeSection === $key])>{{ $label }}</a>
        @endforeach
    </nav>

    @if ($activeSection === 'overview')
        <section class="finance-overview-grid">
            <article class="portal-overview-block">
                <div class="section-heading compact-heading"><div><p class="eyebrow">Billing</p><h2>Current position</h2></div></div>
                <dl class="finance-fact-list"><div><dt>Fee items</dt><dd>{{ number_format($overview['fee_item_count']) }}</dd></div><div><dt>Invoices</dt><dd>{{ number_format($overview['invoice_count']) }}</dd></div><div><dt>Outstanding invoices</dt><dd>{{ number_format($overview['outstanding_invoice_count']) }}</dd></div><div><dt>Completed payments</dt><dd>{{ number_format($overview['payment_count']) }}</dd></div><div><dt>Overpayments</dt><dd>₦{{ number_format($overview['overpayment_total'], 2) }}</dd></div></dl>
            </article>
            <article class="portal-overview-block">
                <div class="section-heading compact-heading"><div><p class="eyebrow">Recent collections</p><h2>Latest payments</h2></div></div>
                <div class="record-list">@forelse ($recentPayments->take(8) as $payment)<article class="record-row compact-record-row"><div><strong>{{ $payment->student->user->fullName() }}</strong><span>{{ $payment->provider->label() }} · {{ $payment->receipt_no ?: $payment->reference }}</span></div><div><span>{{ $payment->paid_at?->format('d M Y') }}</span><strong>₦{{ number_format((float) $payment->amount, 2) }}</strong></div></article>@empty<div class="empty-state">No completed payments are available.</div>@endforelse</div>
            </article>
        </section>
    @elseif ($activeSection === 'fee-items')
        <div class="split-workspace">
            <section class="workspace-primary">
                <div class="section-heading compact-heading"><div><p class="eyebrow">Fee catalogue</p><h2>Created fee items</h2></div></div>
                <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Fee item</th><th>Session</th><th>Term</th><th>Class</th><th>Amount</th><th>Due</th><th>Mandatory</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>@forelse ($feeItems as $item)<tr><td><strong>{{ $item->name }}</strong><small>{{ $item->description }}</small></td><td>{{ $item->academicSession?->name ?? 'All' }}</td><td>{{ $item->term?->name ?? 'All' }}</td><td>{{ $item->schoolClass?->display_name ?? 'All' }}</td><td>₦{{ number_format((float) $item->amount, 2) }}</td><td>{{ $item->due_date?->format('d M Y') ?: '—' }}</td><td>{{ $item->is_mandatory ? 'Yes' : 'No' }}</td><td class="table-actions">@if (! $item->invoices()->exists())<form method="POST" action="{{ route('web.admin.finance.fee-items.destroy', $item) }}">@csrf @method('DELETE')<button class="text-button danger-text" type="submit">Delete</button></form>@endif</td></tr>@empty<tr><td colspan="8">No fee items have been created.</td></tr>@endforelse</tbody></table></div>
            </section>
            <aside class="workspace-aside">
                <section class="plain-panel"><div class="section-heading compact-heading"><div><p class="eyebrow">New charge</p><h2>Create fee item</h2></div></div><form method="POST" action="{{ route('web.admin.finance.fee-items.store') }}" class="form-stack">@csrf<label class="field-group"><span>Name</span><input name="name" required></label><label class="field-group"><span>Session</span><select name="academic_session_id"><option value="">All sessions</option>@foreach ($sessions as $session)<option value="{{ $session->id }}">{{ $session->name }}</option>@endforeach</select></label><label class="field-group"><span>Term</span><select name="term_id"><option value="">All terms</option>@foreach ($terms as $term)<option value="{{ $term->id }}">{{ $term->academicSession?->name }} · {{ $term->name }}</option>@endforeach</select></label><label class="field-group"><span>Class</span><select name="school_class_id"><option value="">All classes</option>@foreach ($classes as $class)<option value="{{ $class->id }}">{{ $class->display_name }}</option>@endforeach</select></label><label class="field-group"><span>Amount</span><input name="amount" type="number" min="0" step="0.01" required></label><label class="field-group"><span>Due date</span><input name="due_date" type="date"></label><label class="field-group"><span>Description</span><textarea name="description" rows="3"></textarea></label><label class="check-row"><input name="is_mandatory" type="checkbox" value="1" checked><span>Generate automatically for matching students</span></label><button class="primary-button" type="submit">Create fee item</button></form></section>
            </aside>
        </div>
    @elseif ($activeSection === 'invoices')
        <div class="split-workspace">
            <section class="workspace-primary"><div class="section-heading compact-heading"><div><p class="eyebrow">Invoice register</p><h2>Recent invoices</h2></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Student</th><th>Fee item</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>@forelse ($invoices->take(100) as $invoice)<tr><td>{{ $invoice->invoice_no }}</td><td><strong>{{ $invoice->student->user->fullName() }}</strong><small>{{ $invoice->student->admission_no }}</small></td><td>{{ $invoice->feeItem?->name }}</td><td>₦{{ number_format((float) $invoice->amount_due, 2) }}</td><td>₦{{ number_format((float) $invoice->amount_paid, 2) }}</td><td>₦{{ number_format((float) $invoice->balance, 2) }}</td><td><span class="status-badge status-{{ $invoice->status }}">{{ str($invoice->status)->headline() }}</span></td></tr>@empty<tr><td colspan="7">No invoices are available.</td></tr>@endforelse</tbody></table></div></section>
            <aside class="workspace-aside"><section class="plain-panel"><div class="section-heading compact-heading"><div><p class="eyebrow">Billing run</p><h2>Generate invoices</h2></div></div><form method="POST" action="{{ route('web.admin.finance.invoices.store') }}" class="form-stack">@csrf<label class="field-group"><span>Fee item</span><select name="fee_item_id" required><option value="">Select fee item</option>@foreach ($feeItems as $item)<option value="{{ $item->id }}">{{ $item->name }} · ₦{{ number_format((float) $item->amount, 2) }}</option>@endforeach</select></label><label class="field-group"><span>Individual student</span><select name="student_id"><option value="">Use class instead</option>@foreach ($students as $student)<option value="{{ $student->id }}">{{ $student->user->fullName() }} · {{ $student->admission_no }}</option>@endforeach</select></label><label class="field-group"><span>Whole class</span><select name="school_class_id"><option value="">Use student instead</option>@foreach ($classes as $class)<option value="{{ $class->id }}">{{ $class->display_name }}</option>@endforeach</select></label><label class="field-group"><span>Optional amount override</span><input name="amount_due" type="number" min="0" step="0.01"></label><label class="field-group"><span>Optional due-date override</span><input name="due_date" type="date"></label><label class="field-group"><span>Notes</span><textarea name="notes" rows="3"></textarea></label><button class="primary-button" type="submit">Generate invoices</button></form></section></aside>
        </div>
    @elseif ($activeSection === 'manual-payment')
        <div class="split-workspace"><section class="workspace-primary"><div class="section-heading compact-heading"><div><p class="eyebrow">Outstanding register</p><h2>Unpaid and part-paid invoices</h2></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Student</th><th>Fee</th><th>Balance</th><th>Due date</th></tr></thead><tbody>@forelse ($invoices->where('balance', '>', 0)->take(100) as $invoice)<tr><td>{{ $invoice->invoice_no }}</td><td>{{ $invoice->student->user->fullName() }}<small>{{ $invoice->student->admission_no }}</small></td><td>{{ $invoice->feeItem?->name }}</td><td><strong>₦{{ number_format((float) $invoice->balance, 2) }}</strong></td><td>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td></tr>@empty<tr><td colspan="5">No outstanding invoices are available.</td></tr>@endforelse</tbody></table></div></section><aside class="workspace-aside"><section class="plain-panel"><div class="section-heading compact-heading"><div><p class="eyebrow">Finance desk</p><h2>Record manual payment</h2></div></div><form method="POST" action="{{ route('web.admin.finance.manual-payments.store') }}" class="form-stack">@csrf<label class="field-group"><span>Invoice</span><select name="fee_invoice_id" required><option value="">Select invoice</option>@foreach ($invoices->where('balance', '>', 0) as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->invoice_no }} · {{ $invoice->student->user->fullName() }} · ₦{{ number_format((float) $invoice->balance, 2) }}</option>@endforeach</select></label><label class="field-group"><span>Amount received</span><input name="amount" type="number" min="1" step="0.01" required></label><label class="field-group"><span>Channel</span><select name="channel" required><option value="cash">Cash</option><option value="bank-transfer">Bank transfer</option><option value="pos">POS</option><option value="cheque">Cheque</option><option value="school-office">Other school office</option></select></label><label class="field-group"><span>Payment date/time</span><input name="paid_at" type="datetime-local"></label><label class="field-group"><span>Note</span><textarea name="note" rows="3"></textarea></label><button class="primary-button" type="submit">Record and issue receipt</button></form></section></aside></div>
    @elseif ($activeSection === 'student-balances')
        <form method="GET" class="filter-bar"><input type="hidden" name="section" value="student-balances"><label class="field-group filter-grow"><span>Search student balances</span><input name="student_search" value="{{ $filters['student_search'] ?? '' }}" placeholder="Student name, admission number, email or class"></label><button class="secondary-button" type="submit">Search</button></form><div class="record-list">@forelse ($studentBalanceRows as $row)<details class="record-disclosure"><summary><span><strong>{{ $row['student']->user->fullName() }}</strong><small>{{ $row['student']->admission_no }} · {{ $row['student']->schoolClass?->display_name }}</small></span><span>₦{{ number_format($row['outstanding_total'], 2) }} outstanding</span></summary><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Invoice</th><th>Fee item</th><th>Due</th><th>Paid</th><th>Balance</th></tr></thead><tbody>@foreach ($row['unpaid_items'] as $invoice)<tr><td>{{ $invoice->invoice_no }}</td><td>{{ $invoice->feeItem?->name }}</td><td>₦{{ number_format((float) $invoice->amount_due, 2) }}</td><td>₦{{ number_format((float) $invoice->amount_paid, 2) }}</td><td>₦{{ number_format((float) $invoice->balance, 2) }}</td></tr>@endforeach</tbody></table></div></details>@empty<div class="empty-state">No matching balance records are available.</div>@endforelse</div>
    @elseif ($activeSection === 'class-bills')
        <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Class</th><th>Students</th><th>Invoices</th><th>Debtors</th><th>Expected</th><th>Collected</th><th>Outstanding</th><th>Rate</th></tr></thead><tbody>@foreach ($classBillingRows as $row)<tr><td><strong>{{ $row['class']->display_name }}</strong></td><td>{{ $row['student_count'] }}</td><td>{{ $row['invoice_count'] }}</td><td>{{ $row['students_with_debt'] }}</td><td>₦{{ number_format($row['expected_total'], 2) }}</td><td>₦{{ number_format($row['collected_total'], 2) }}</td><td>₦{{ number_format($row['outstanding_total'], 2) }}</td><td>{{ number_format($row['collection_rate'], 1) }}%</td></tr>@endforeach</tbody></table></div>
    @elseif ($activeSection === 'payment-summary')
        <section class="finance-summary-columns">@foreach ([['title' => 'By provider', 'rows' => $paymentSummary['providerBreakdown'], 'label' => 'label'], ['title' => 'By channel', 'rows' => $paymentSummary['channelBreakdown'], 'label' => 'channel'], ['title' => 'Daily collections', 'rows' => $paymentSummary['dailyCollection'], 'label' => 'day']] as $summary)<article><h2>{{ $summary['title'] }}</h2><div class="record-list">@forelse ($summary['rows'] as $row)<div class="record-row compact-record-row"><div><strong>{{ $row[$summary['label']] }}</strong><span>{{ $row['count'] }} payments</span></div><div><strong>₦{{ number_format($row['total'], 2) }}</strong></div></div>@empty<div class="empty-state">No collection data.</div>@endforelse</div></article>@endforeach</section>
    @elseif ($activeSection === 'recent-payments')
        <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Student</th><th>Date</th><th>Provider</th><th>Channel</th><th>Amount</th><th><span class="sr-only">Action</span></th></tr></thead><tbody>@forelse ($recentPayments as $payment)<tr><td>{{ $payment->receipt_no }}<small>{{ $payment->reference }}</small></td><td>{{ $payment->student->user->fullName() }}<small>{{ $payment->student->admission_no }}</small></td><td>{{ $payment->paid_at?->format('d M Y H:i') }}</td><td>{{ $payment->provider->label() }}</td><td>{{ str($payment->channel ?: 'Unspecified')->headline() }}</td><td>₦{{ number_format((float) $payment->amount, 2) }}</td><td class="table-actions"><a href="{{ route('web.admin.finance.receipt', $payment) }}">Receipt</a></td></tr>@empty<tr><td colspan="7">No completed payments are available.</td></tr>@endforelse</tbody></table></div>
    @elseif ($activeSection === 'overpayments')
        <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Student</th><th>Invoice</th><th>Fee item</th><th>Due</th><th>Paid</th><th>Overpayment</th><th>Last payment</th></tr></thead><tbody>@forelse ($overpaymentRows as $row)<tr><td>{{ $row['student']->user->fullName() }}<small>{{ $row['student']->admission_no }}</small></td><td>{{ $row['invoice']->invoice_no }}</td><td>{{ $row['invoice']->feeItem?->name }}</td><td>₦{{ number_format((float) $row['invoice']->amount_due, 2) }}</td><td>₦{{ number_format((float) $row['invoice']->amount_paid, 2) }}</td><td><strong>₦{{ number_format($row['overpayment'], 2) }}</strong></td><td>{{ $row['last_payment_at']?->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="7">No overpayments are recorded.</td></tr>@endforelse</tbody></table></div>
    @elseif ($activeSection === 'payment-progression')
        <div class="record-list">@forelse ($paymentProgressionRows as $row)<article class="payment-progress-row"><div><strong>{{ $row['student']->user->fullName() }} · {{ $row['invoice']->feeItem?->name }}</strong><span>{{ $row['invoice']->invoice_no }} · ₦{{ number_format((float) $row['invoice']->balance, 2) }} balance</span></div><div class="progress-track"><span style="width: {{ $row['progress'] }}%"></span></div><strong>{{ number_format($row['progress'], 1) }}%</strong></article>@empty<div class="empty-state">No invoice progression records are available.</div>@endforelse</div>
    @endif
@endsection
